// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeuscslngjdjluqssfgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldXNjc2xuZ2pkamx1cXNzZmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTk4NzcsImV4cCI6MjA2NDQzNTg3N30.Pupr_dY7QCDG1Lvwei4D1CRM2sxSZ6tKDi3OywCVub4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);